name: Call Remote E2E

on:
  pull_request:
    branches: [stage]

jobs:
  call-e2e:
    uses: ecommerce-microservices-lab/ci-templates/.github/workflows/call_remote_e2e.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}